name: Report
version: 1.0.0
main: com.example.report.ReportPlugin
api-version: 1.20
author: Master_Fox_Minecraft_Sam111
description: Report

commands:
  report:
    description: 打开举报GUI
    usage: /report
    aliases: [rep, reportgui]
    permission: report.use
    
  reportlist:
    description: 查看举报列表（仅OP）
    usage: /reportlist
    aliases: [reports, reportlistgui]
    permission: report.list

permissions:
  report.*:
    description: 所有举报插件权限
    default: op
    children:
      report.use: true
      report.list: true
  report.use:
    description: 使用举报功能
    default: true
  report.list:
    description: 查看举报列表
    default: op
